# Generated by Django 3.2.11 on 2022-01-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField()),
                ('favorite', models.BooleanField()),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste', to='todo.todolist')),
            ],
        ),
    ]
